fosswebsite/urls.py
# created by Chirath R, chirath.02@gmail.com
"""fosswebsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from attendance.views import SSIDNameAPIView, MarkAttendanceAPIView
from clubManagement.views import StatusReportDetailApiView
from fosswebsite import settings
from registration.views import UserViewSet, UserInfoViewSet
from .views import Home


router = routers.DefaultRouter()
router.register(r'status-report', StatusReportDetailApiView)
router.register(r'user', UserViewSet)
router.register(r'user-info', UserInfoViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('registration.urls')),
    # this file is invisible
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^club/', include('clubManagement.urls')),
    url(r'^foss/', include('promotion.urls')),
    url(r'^achievements/', include('achievements.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^timeline/', include('timeline.urls')),
    url(r'^workshop/', include('workshop.urls')),
    url(r'^notices/', include('noticeBoard.urls')),
    url(r'^resources/', include('technical_resources.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^attendance/', include('attendance.urls')),
    url(r'^api/auth/', include('rest_framework.urls')),
    url(r'^api/auth/token/$', obtain_jwt_token),
    url(r'^api/ssid-name/$',  SSIDNameAPIView.as_view()),
    url(r'^api/attendance/mark/$',  MarkAttendanceAPIView.as_view()),
    url(r'^api/', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
# created by Navaneeth S, navisk13@gmail.com
from django.conf.urls import url

from documents.views import DocumentListView, DocumentCreateView, DocumentDeleteView, DocumentUpdateView

urlpatterns = [
    url(r'^$', DocumentListView.as_view(), name='document'),
    url(r'^create/$', DocumentCreateView.as_view(), name='document_create'),
    url(r'^(?P<pk>[0-9]+)/update/$', DocumentUpdateView.as_view(), name='document_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', DocumentDeleteView.as_view(), name='document_delete'),
]

projects/models.py
# created by Chirath R, chirath.02@gmail.com
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Project(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=300)
    url = models.URLField(max_length=400, null=True, blank=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='project/', null=True, blank=True)
    date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.created_by.username + ' ' + self.title

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'pk': self.id})


class ProjectScreenShot(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/')

    def __str__(self):
        return self.project


class ProjectMembers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date_assigned = models.DateTimeField(auto_now_add=True, auto_now=False)


class Language(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    language = models.CharField(max_length=100)

projects/templates/projects/language_form.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->
{% extends 'base/base.html' %}

{% block title %} Add Language {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 card">
                        <div class="card-block">
                            <h1 class="card-title">Language/Framework</h1>
                            <hr>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" name="language" id="language"
                                           value="{{ object.language }}" placeholder="Language">
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="notifications">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        {{ field.label }}: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 70px;
        }
        .notifications {
            position: fixed;
            top: 90px;
            right: 0;
            z-index: 1000;
            font-size: 0.7em;
            max-width: 90%;
        }
    </style>
{% endblock %}

projects/templates/projects/project_confirm_delete.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->

{% extends 'base/base.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <form class="card" action="" method="post">
                            <div class="card-block">
                                {% csrf_token %}
                                <h2>Delete {{ object.title }}?</h2>
                                <button type="submit" class="btn btn-danger">Yes, continue</button>
                            </div>
                        </form>
                        <a href="{% url 'project_detail' object.id  %}"><button class="btn btn-info">No, take me out of here</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 80px;
        }

        .btn {
            margin-right: 10px;
            margin-top: 20px;
        }
    </style>
{% endblock %}

projects/templates/projects/project_detail.html
 <!-- Created by Navaneeth S, navisk13@gmail.com -->
{% extends 'base/base.html' %}

{% block title %} {{ object.title }} {% endblock %}

{% load static %}

{% block script %}
    <!-- Latest compiled and minified JavaScript -->
{% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->

            <div class="container">
                <div class="row">
                    <h1 class="head col-md-12">Project Details</h1>
                    <div class="col-md-8">
                        <div class="card mb-3">
                            {% if object.image %}
                                <img class="card-img-top img-fluid" src="/static/media/{{ object.image }}">
                            {% else %}
                                <img class="card-img-top img-fluid" src="{% static 'projects/images/default.png' %}">
                            {% endif %}
                            <div class="card-block">
                                <h4 class="card-title">{{ object.title }}</h4>
                                <p class="card-text">{{ object.description }}</p>
                                <p class="card-text">Link: <a href="{{ object.url }}">{{ object.url }}</a></p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        Added by : {{ object.created_by.first_name }} {{ object.created_by.last_name }},
                                        {{ object.date }}
                                    </small>
                                </p>
                                {% if edit_permission %}
                                    <a href="{% url 'project_update' object.id %}">
                                        <button type="submit" class="btn btn-primary add-btn">Update</button>
                                    </a>
                                    <a href="{% url 'project_delete' object.id %}">
                                        <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                    </a>
                                    <a href="{% url 'image_list' object.id %}">
                                        <button type="submit" class="btn btn-success add-btn">View Screenshots</button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>

                        <div class="card student-form" id="student-form" style="display: none">
                            <div class="card-block">
                                <form class="form-group col-md-6" action="" method="post">
                                    {% csrf_token %}
                                    <label for="exampleInputEmail1"><h4>Add Student</h4></label>
                                    <div class="dropdown">
                                        <input id="search" onkeyup="myFunction()" class="form-control"
                                               data-toggle="dropdown" placeholder="Search..." autocomplete="off">
                                        <input type="hidden" id="search-id" name="user_id">
                                        <div class="dropdown-menu" id="search-results">
                                            {% for user in all_users %}
                                                <p onclick="addText({{ user.id }}, '{{ user.first_name }} {{ user.last_name }}')"
                                                   class="dropdown-item">{{ user.first_name }} {{ user.last_name }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <small id="emailHelp" class="form-text text-muted">Search for a student above.
                                    </small>
                                    <button type="submit" class="btn btn-secondary add-btn">Add</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <ul class="list-group col-md-4">
                            <div class="margin-20"></div>
                            <li class="list-group-item justify-content-between">
                                <h5>Project members</h5>
                                <span class="badge badge-default badge-pill">{{ user_count }}</span>
                              </li>
                            {% for project in project_list %}
                              <li class="list-group-item justify-content-between">
                                {{ project.user.first_name }}  {{ project.user.last_name }}
                                  <form method="post" action="{% url "project_member_delete" project.id %}">
                                       {% csrf_token %}
                                      <button type="submit" class="close">×</button>
                                  </form>
                              </li>
                            {% endfor %}
                            {% if edit_permission %}
                            <div onclick="showForm()" class="col-md-1 offset-md-3">
                                <button class="btn btn-secondary add-btn">
                                    Add student
                                </button>
                            </div>
                            {% endif %}
                            <li style="margin-top: 20px " class="list-group-item justify-content-between">
                                <h5>Languages & Frameworks</h5>
                            </li>
                                {% for i in languages %}

                                <li class="list-group-item justify-content-between">
                                <h6>{{ i.language }}</h6><br>
                                <form method="post" action="{% url "language_delete" i.id %}">
                                       {% csrf_token %}
                                      <button type="submit" class="close">×</button>
                                </form>
                                {% endfor %}
                                </li>
                            {% if edit_permission %}
                            <div class="col-md-6 offset-md-3">
                                <a href="{% url 'language_create' object.id %}"><button class="btn btn-secondary add-btn">Add Language</button></a>
                            </div>
                            {% endif %}
                    </ul>
                </div>
            </div>

        </div>
    </div>

    {% include 'base/footer.html' %}

    <style>

        .container {
            margin-top: 50px;
        }

        .add-btn {
            margin-top: 20px;
        }

        .margin-20 {
            margin: 24px;
        }

        .head {
            margin: 30px 0;
        }

        .link {
            text-decoration: none !important;
            color:black;
        }
    </style>

    <script>
        function showForm() {
            var form = document.getElementById('student-form');
            if (form.style.display === 'none') {
                form.style.display = 'block';
            }
            else {
                form.style.display = 'none';
            }
        }

        function myFunction() {
            // Declare variables
            var input, filter, items, i;
            input = document.getElementById('search');
            filter = input.value.toUpperCase();
            items = document.getElementsByClassName('dropdown-item');

            // Loop through all list items, and hide those who don't match the search query
            for (i = 0; i < items.length; i++) {
                if (items[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    items[i].style.display = "";
                } else {
                    items[i].style.display = "none";
                }
            }
        }

        function addText(id, name) {
            var inp1 = document.getElementById('search');
            var inp2 = document.getElementById('search-id');
            inp1.value = name;
            inp2.value = id;
        }
    </script>
{% endblock %}

projects/templates/projects/project_form.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->
{% extends 'base/base.html' %}
{% load static %}
{% block title %} New Project {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 card">
                        <div class="card-block">
                            <h1 class="card-title">Project</h1>
                            <hr>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Title</label>
                                    <input type="text" class="form-control" name="title" id="name"
                                           value="{{ object.title }}" placeholder="Title">
                                </div>
                                <div class="form-group">
                                    <label for="url">Project Url</label>
                                    <input type="text" class="form-control" name="url" id="url"
                                           value="{{ object.url }}" placeholder="Url">
                                </div>
                                <label for="file">
                                    Image
                                    {% if object.image %}
                                        : {{ object.image }}
                                    {% endif %}
                                </label><br>
                                <div class="custom-file form-group">
                                    <input type="file" name="image" id="file" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea id="description" name="description" class="form-control"
                                              placeholder="Description" rows="5">{{ object.description }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="date">Date</label>
                                    <div class='input-group date' id='datetimepicker1'>
                                        <input id="date" name="date" value="{{ object.date|date:'y-m-d' }}"
                                               type='text' placeholder="YYYY-MM-DD" class="form-control"/>
                                        <span class="input-group-addon">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="notifications">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        {{ field.label }}: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 70px;
        }
        .notifications {
            position: fixed;
            top: 90px;
            right: 0;
            z-index: 1000;
            font-size: 0.7em;
            max-width: 90%;
        }
    </style>
{% endblock %}


{% block script %}
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script src="{% static 'base/js/moment.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap-datetimepicker.min.js' %}"></script>
    <link href="{% static 'base/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                icons: {
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-arrow-up",
                    down: "fa fa-arrow-down"
                },
                format: 'YYYY-MM-DD',
                widgetPositioning: {
                    horizontal: 'right',
                    vertical: 'top'
                }
            });
        });
    </script>
{% endblock %}

projects/templates/projects/project_list.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Projects {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="card col-md-12">
                        <div class="card-block">
                            <h1 class="card-title">Projects</h1>
                            <hr>
                            <div class="row">
                                {% for object in object_list %}
                                    <div class="col-md-6">
                                        <div class="card">
                                            {% if object.image %}
                                                <img class="card-img-top img-fluid" src="/static/media/{{ object.image }}">
                                            {% else %}
                                                <img class="card-img-top img-fluid"
                                                     src="{% static 'projects/images/default.png' %}">
                                            {% endif %}
                                            <div class="card-block">
                                                <h3 class="card-title">{{ object.title }}</h3>
                                                <p class="card-text">{{ object.description }}</p>
                                                <a href="{% url 'project_detail' object.id %}"
                                                   class="btn btn-primary">More info
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}

                                {% if request.user.is_authenticated %}

                                <div class="col-md-12">
                                    <div class="container">
                                        <a href="{% url 'project_create' %}">
                                            <button class="btn btn-secondary">Add new</button>
                                        </a>
                                    </div>
                                </div>

                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <style>
        .card {
            margin: 10px;
        }

        .container {
            margin-top: 50px;
        }
    </style>
{% endblock %}

projects/templates/projects/projectscreenshot_form.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->
{% extends 'base/base.html' %}

{% block title %} Add Screenshot {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 card">
                        <div class="card-block">
                            <h1 class="card-title">Add Screenshot</h1>
                            <hr>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="custom-file form-group">
                                    <input type="file" name="image" id="file" class="form-control">
                                </div>
                                <br>
                                <br>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="notifications">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        {{ field.label }}: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 70px;
        }
        .notifications {
            position: fixed;
            top: 90px;
            right: 0;
            z-index: 1000;
            font-size: 0.7em;
            max-width: 90%;
        }
    </style>
{% endblock %}

projects/templates/projects/projectscreenshot_list.html
<!-- Created by Navaneeth S, navisk13@gmail.com -->

{% extends 'base/base.html' %}
{% load static %}
{% block title %} Screenshots {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
        <div class="container">
            <h1>Screenshots</h1>
            <div class="row">
                {% for object in object_list %}
                    <div class="col-md-6">
                        <img class="img" src="/static/media/{{ object.image }}">
                        <div class="div2">
                            <form method="post" action="{% url "image_delete" object.id %}">
                            {% csrf_token %}
                            <button type="submit" class="button">×</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
                        <div class="col-md-12">
                         <a href="{% url 'image_create' id %}">
                            <button type="submit" class="btn btn-primary add-btn">Add Image</button>
                         </a>
                        </div>
            </div>
        </div>
    </div>
</div>





    {% include 'base/footer.html' %}

    <style>

        .container {
            margin-top: 50px;
        }

        .img {
            height: 270px;
            width: 540px;
            padding: 10px;
        }

        .button {
            display: absolute;
            background-color: transparent;
            border: none;
            font-size: 25px;
         }

        .div2 {
            position: absolute;
            left: 518px;
            bottom: 234px;
        }

        .btn {
            margin-left: 20px;
            margin-top: 20px;

        }
    </style>
{% endblock %}