clubManagement/urls.py
# created by Chirath R, chirath.02@gmail.com
from django.conf.urls import url

from clubManagement.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        r'^attendance-report/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_all'
    ),
    url(
        r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_batch'
    ),
    url(
        r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$',
        MonthAttendanceReportView.as_view(),
        name='attendance_report_month'
        ),
    url(
        r'^attendance-report-student/(?P<year>[0-9]+)/(?P<user_id>[0-9]+)/$',
        login_required(YearStudentAttendanceReportView.as_view()),
        name='attendance_report_year'
    ),
    url(
        r'^attendance/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_all'
    ),
    url(
        r'^attendance/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_batch'
    ),

    # Responsibilities
    url(r'^responsibility/$', login_required(ResponsibilityListView.as_view()),
        name='responsibility'),
    url(r'^responsibility/(?P<pk>[0-9]+)/$',
        login_required(ResponsibilityDetailView.as_view()),
        name='responsibility_detail'),
    url(r'^responsibility/create/$',
        login_required(ResponsibilityCreateView.as_view()),
        name='responsibility_create'),
    url(r'^responsibility/(?P<pk>[0-9]+)/update/$',
        login_required(ResponsibilityUpdateView.as_view()),
        name='responsibility_update'),
    url(r'^responsibility/(?P<pk>[0-9]+)/delete/$',
        login_required(ResponsibilityDeleteView.as_view()),
        name='responsibility_delete'),
    url(r'^responsibility-student/(?P<pk>[0-9]+)/delete/$',
        StudentResponsibilityDeleteView.as_view(),
        name='student_responsibility_delete'
        ),

    # Teams
    url(r'^teams/$', TeamListView.as_view(), name='team'),
    url(r'^teams/(?P<pk>[0-9]+)/$', TeamDetailView.as_view(),
        name='team_detail'),
    url(r'^teams/create/$', login_required(TeamCreateView.as_view()),
        name='team_create'),
    url(r'^teams/(?P<pk>[0-9]+)/update$',
        login_required(TeamUpdateView.as_view()), name='team_update'),
    url(r'^teams/(?P<pk>[0-9]+)/delete/$',
        login_required(TeamDeleteView.as_view()), name='team_delete'),
    url(r'^teams-member/(?P<pk>[0-9]+)/delete/$',
        login_required(TeamMemberDeleteView.as_view()),
        name='team_member_delete'),

    # Status update
    url(r'^status-update/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(MonthlyStatusUpdateDetailView.as_view()),
        name='monthly-status-update-detail'),
    url(r'^status-update/(?P<day>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(StatusUpdateDetailView.as_view()),
        name='status-update-detail'),


    # index
    url(r'^$', login_required(IndexView.as_view()), name='club'),
]

fosswebsite/urls.py
# created by Chirath R, chirath.02@gmail.com
"""fosswebsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from attendance.views import SSIDNameAPIView, MarkAttendanceAPIView
from clubManagement.views import StatusReportDetailApiView
from fosswebsite import settings
from registration.views import UserViewSet, UserInfoViewSet
from .views import Home


router = routers.DefaultRouter()
router.register(r'status-report', StatusReportDetailApiView)
router.register(r'user', UserViewSet)
router.register(r'user-info', UserInfoViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('registration.urls')),
    # this file is invisible
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^club/', include('clubManagement.urls')),
    url(r'^foss/', include('promotion.urls')),
    url(r'^achievements/', include('achievements.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^timeline/', include('timeline.urls')),
    url(r'^workshop/', include('workshop.urls')),
    url(r'^notices/', include('noticeBoard.urls')),
    url(r'^resources/', include('technical_resources.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^attendance/', include('attendance.urls')),
    url(r'^api/auth/', include('rest_framework.urls')),
    url(r'^api/auth/token/$', obtain_jwt_token),
    url(r'^api/ssid-name/$',  SSIDNameAPIView.as_view()),
    url(r'^api/attendance/mark/$',  MarkAttendanceAPIView.as_view()),
    url(r'^api/', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
# created by Navaneeth S, navisk13@gmail.com
from django.conf.urls import url

from documents.views import DocumentListView, DocumentCreateView, DocumentDeleteView, DocumentUpdateView

urlpatterns = [
    url(r'^$', DocumentListView.as_view(), name='document'),
    url(r'^create/$', DocumentCreateView.as_view(), name='document_create'),
    url(r'^(?P<pk>[0-9]+)/update/$', DocumentUpdateView.as_view(), name='document_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', DocumentDeleteView.as_view(), name='document_delete'),
]

clubManagement/models.py
# -*- coding: utf-8 -*-
# created by Chirath R, chirath.02@gmail.com
from __future__ import unicode_literals

import json

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.datetime_safe import date
from projects.models import Project
from registration.models import UserInfo


class Team(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='team/', blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team_detail', kwargs={'pk': self.id})


class TeamMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    date_assigned = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.username + " - " + self.team.name


class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                 related_name="added_by")
    date = models.DateField()
    modified_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    attendance = models.BooleanField(default=False)

    def __str__(self):
        if self.attendance:
            return self.user.username + " " + str(self.date) + " - present"
        else:
            return self.user.username + " " + str(self.date) + " - absent"


class Responsibility(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                   related_name='created_by')
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('responsibility_detail', kwargs={'pk': self.pk})


class StudentResponsibility(models.Model):
    responsibility = models.ForeignKey(Responsibility, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class StatusUpdate(models.Model):
    """
    The status update for each data is stored as a string
    `user_id1 Y/N, user_id Y/N, .....`
    """
    date = models.DateField()
    value = models.CharField(max_length=1000)
    data = models.CharField(max_length=5000, blank=True)

    def get_value_dict(self):
        status_list = self.value.split(', ')
        status_dict = {}

        for status in status_list:
            user_id, status = status.split(' ')
            status_dict[int(user_id)] = status

        return status_dict

    def process_report(self):
        """
        saves a dict with key as the year and value as a list of user to the
        data field
        list-of-users = [[user, status]] where status is  a string with default
        value N
        :return:  {'year': {'name': 'full_name', 'status': 'Y'}}
        """
        status_dict = self.get_value_dict()

        # no status reports found
        if not status_dict:
            return

        start_year = date.today().year

        if date.today().month < 8:
            start_year -= 1

        user_data = {}

        for year in range(start_year, start_year - 4, -1):
            user_info_list = UserInfo.objects.filter(year=year)
            user_list = {}
            for user_info in user_info_list:
                if user_info.user.is_active and not user_info.is_mentor:
                    status = status_dict.get(int(user_info.user.pk), None)
                    if status:
                        user_list[user_info.user.get_full_name()] = status
                    else:
                        user_list[user_info.user.get_full_name()] = 'N'

            if user_list:
                user_data[str(year)] = user_list

        self.data = json.dumps(user_data)
        self.save()

    def get_report(self):
        """
        Returns a dict with {'year': {'name': 'full_name', 'status': 'Y'}}
        :return: dict
        """
        if not self.data:
            self.process_report()
        return json.loads(self.data)

    def __str__(self):
        return str(self.date)

clubManagement/templates/clubManagement/attendance_add.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Add attendance {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <div class="container">
                <form class="row" action="" method="post">
                    {% csrf_token %}
                    {% for attendance in attendance_list %}
                        <h2 class="header col-xs-12 col-md-12">{{ attendance.1 }}</h2>
                        {% for att in attendance.0 %}
                            <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                                    {% if request.user.is_superuser %}
                                 onclick="click_attendance('{{ att.user.username }}')" {% endif %}
                                 id="{{ att.user.username }}_div" style="white-space: normal">
                                <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                                <input type="checkbox" style="display: None" id="{{ att.user.username }}" value="True"
                                       name="{{ att.user.username }}" {% if att.attendance %}checked{% endif %}>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                    <button type="reset" onclick="changeDay(-1)" class="col-md-2 col-sm-6 btn">Previous</button>
                    {% if request.user.is_superuser %}
                        <button type="submit" class="col-md-2 offset-md-3 col-sm-6 btn btn-primary save-btn">Save
                        </button>
                    {% endif %}
                    <button type="reset" onclick="changeDay(1)" class="col-md-2 offset-md-3 col-sm-6 btn">Next</button>
                </form>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <script>
        function changeDay(i) {
            var variables, year, month, day, link, date;

            variables = window.location.href.split("/");

            year = variables[(variables.length - 4)];
            month = variables[variables.length - 3] - 1;
            day = variables[variables.length - 2];

            if (variables.length === 9)
                link = '/club/attendance/';
            else
                link = '/club/attendance/' + parseInt(variables[variables.length - 5]) + '/';

            date = new Date(year, month, day, 0, 0, 0);
            date.setDate(date.getDate() + i);
            link += date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();

            window.location = link;
        }
    </script>

    <style>
        .btn {
            margin: 10px;
        }

        .save-btn {
            padding: 10px 0;
        }

        .names {
            height: 80px;
        }

        .link {
            height: 100%;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        form {
            margin: 30px 0;
        }

        .header {
            padding-top: 20px;
            text-align: center;
        }
    </style>

    {% block script %}
        <script src="{% static 'clubManagement/js/attendance.js' %}"></script>
    {% endblock %}
{% endblock %}

clubManagement/templates/clubManagement/attendance_daily.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Add attendance {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <div class="container">
                <h2 class="header">{{ head }}</h2>
                <div class="row form">
                {% csrf_token %}
                    {% for att in attendance_list %}
                        <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                             id="{{ att.user.username }}_div" style="white-space: normal">
                            <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                        </div>
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                </div>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <style>
        .btn {
            margin: 10px;
        }

        .save-btn {
            padding: 10px 0;
        }

        .names {
            height: 80px;
        }



        .form {
            margin: 30px 0;
        }
        .header {
            padding-top: 20px;
            text-align: center;
        }

        .link {
            height: 100%;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
{% endblock %}

clubManagement/templates/clubManagement/responsibility_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="card" action="" method="post" >
                                <div class="card-block">
                                    {% csrf_token %}
                                    <h2>Delete {{ object.name }}?</h2>
                                    <button type="submit" class="btn btn-danger">Yes, continue</button>
                                </div>
                            </form>
                            <a href="{% url 'responsibility_detail' object.id %}"><button class="btn btn-info">No, take me out of here</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 80px;
        }
    .btn {
        margin-right: 10px;
        margin-top: 20px;
    }
    </style>
{% endblock %}

clubManagement/templates/clubManagement/responsibility_detail.html
{% extends 'base/base.html' %}

{% block title %} {{ object.name }} {% endblock %}

{% load static %}

{% block script %}
    <!-- Latest compiled and minified JavaScript -->
{% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->

                <div class="container">
                    <div class="row">

                        <div class="col-md-8">
                            <h3>Club Responsibility</h3>
                            <div class="card mb-3">
                              <img class="card-img-top" src="{% static 'clubManagement/image/great_power_great_responsibility.jpg' %}">
                              <div class="card-block">
                                <h4 class="card-title">{{ object.name }}</h4>
                                <p class="card-text">{{ object.description }}</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                       Added by : {{ object.created_by.first_name }} {{ object.created_by.last_name }}
                                    </small>
                                </p>
                                  {% if edit_permission %}
                                <a href="{% url 'responsibility_update' object.id %}">
                                    <button type="submit" class="btn btn-primary add-btn">Update</button>
                                </a>
                                <a href="{% url 'responsibility_delete' object.id %}">
                                    <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                </a>
                                  {% endif %}
                              </div>
                            </div>

                            <div class="card student-form" id="student-form" style="display: none">
                              <div class="card-block">
                                <form class="form-group col-md-6" action="" method="post">
                                    {% csrf_token %}
                                    <label for="exampleInputEmail1"><h4>Add Student</h4></label>
                                    <div class="dropdown">
                                        <input id="search" onkeyup="myFunction()" class="form-control" data-toggle="dropdown" placeholder="Search..." autocomplete="off">
                                        <input type="hidden" id="search-id" name="user_id">
                                        <div class="dropdown-menu" id="search-results">
                                            {% for user in all_users %}
                                                <p onclick="addText({{ user.id }}, '{{ user.first_name }} {{ user.last_name }}')" class="dropdown-item">{{ user.first_name }} {{ user.last_name }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <small id="emailHelp" class="form-text text-muted">Search for a student above.</small>
                                    <button type="submit" class="btn btn-secondary add-btn">Add</button>
                                  </form>
                              </div>
                            </div>
                        </div>

                        <ul class="list-group col-md-4">
                            <div class="margin-20"></div>
                            <li class="list-group-item justify-content-between">
                                <h5>Student's responsible</h5>
                                <span class="badge badge-default badge-pill">{{ user_count }}</span>
                              </li>
                            {% for resp in responsibility_list %}
                              <li class="list-group-item justify-content-between">
                                {{ resp.user.first_name }}  {{ resp.user.last_name }}
                                <form method="post" action="{% url "student_responsibility_delete" resp.id %}">
                                       {% csrf_token %}
                                      <button type="submit" class="close">×</button>
                                  </form>
                              </li>
                            {% endfor %}
                            {% if edit_permission %}
                            <div onclick="showForm()" class="col-md-6 offset-md-3">
                                <button class="btn btn-secondary add-btn">
                                    Add student
                                </button>
                            </div>
                            {% endif %}
                        </ul>

                    </div>
                </div>

            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 50px;
        }
        .add-btn {
            margin-top: 20px;
        }
        .margin-20 {
            margin: 24px;
        }
    </style>

    <script>
        function showForm() {
            var form = document.getElementById('student-form');
            if(form.style.display === 'none') {
                form.style.display = 'block';
            }
            else {
                form.style.display = 'none';
            }
        }

        function myFunction() {
            // Declare variables
            var input, filter, items, i;
            input = document.getElementById('search');
            filter = input.value.toUpperCase();
            items = document.getElementsByClassName('dropdown-item');

            // Loop through all list items, and hide those who don't match the search query
            for (i = 0; i < items.length; i++) {
                if (items[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    items[i].style.display = "";
                } else {
                    items[i].style.display = "none";
                }
            }
        }

        function addText(id, name) {
            var inp1 = document.getElementById('search');
            var inp2 = document.getElementById('search-id');
            inp1.value = name;
            inp2.value = id;
        }
    </script>
{% endblock %}

clubManagement/templates/clubManagement/status-report-mail-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Status update report {{ date }}</title>
</head>
<body>
    <h2>Status update report {{ date }}</h2>

    <h3>Students who didn't sent status updates</h3>
    {% for year, value in status_update.items %}
        <h4>{{ year }}</h4>
        <ol>
            {% for name, status in value.items %}
                {% ifequal status "N" %}
                    <li>{{ name }}</li>
                {% endifequal %}
            {%  endfor %}
        </ol>
    {% endfor %}

    <h3>Students who sent status updates</h3>

    {% for year, value in status_update.items %}
        <h4>{{ year }}</h4>
        <ol>
            {% for name, status in value.items %}
                {% ifequal status "Y" %}
                    <li>{{ name }}</li>
                {% endifequal %}
            {%  endfor %}
        </ol>
    {% endfor %}

    {% if url %}
        <p>More info: <a href="{{ url }}">{{ url }}</a></p>
    {% endif %}

</body>
</html>

clubManagement/templates/clubManagement/status-report-monthly-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Status update report {{ date }}</title>
</head>
<body>
    <h2>Status update report {{ date }}</h2>
    <h3>Total: {{ total }}</h3>


    {% for year, value in status_update.items %}
        <h4>{{ year }}</h4>
        <ol>
            {% for name, status in value.items %}
                    <li>{{ name }} - {{ status }}</li>
            {%  endfor %}
        </ol>
    {% endfor %}

</body>
</html>

clubManagement/templates/clubManagement/team_detail.html
{% extends 'base/base.html' %}

{% block title %} {{ object.name }} {% endblock %}

{% load static %}

{% block script %}
    <!-- Latest compiled and minified JavaScript -->
{% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->

            <div class="container">
                <div class="row">

                    <div class="col-md-8">
                        <h3>Team details</h3>
                        <div class="card mb-3">
                            <img class="card-img-top img-fluid" src="/static/media/{{ object.image }}">
                            <div class="card-block">
                                <h4 class="card-title">{{ object.name }}</h4>
                                <p class="card-text">{{ object.description }}</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        Added by : {{ object.created_by.first_name }} {{ object.created_by.last_name }}
                                    </small>
                                </p>
                                {% if edit_permission %}
                                    <a href="{% url 'team_update' object.id %}">
                                        <button type="submit" class="btn btn-primary add-btn">Update</button>
                                    </a>
                                    <a href="{% url 'team_delete' object.id %}">
                                        <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>

                        <div class="card student-form" id="student-form" style="display: none">
                            <div class="card-block">
                                <form class="form-group col-md-6" action="" method="post">
                                    {% csrf_token %}
                                    <div class="dropdown">
                                        <input id="search" onkeyup="myFunction()" class="form-control"
                                               data-toggle="dropdown" placeholder="Search..." autocomplete="off">
                                        <input type="hidden" id="search-id" name="user_id">
                                        <div class="dropdown-menu" id="search-results">
                                            {% for user in all_users %}
                                                <p onclick="addText({{ user.id }}, '{{ user.first_name }} {{ user.last_name }}')"
                                                   class="dropdown-item">{{ user.first_name }} {{ user.last_name }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <small id="emailHelp" class="form-text text-muted">Search for a student above.
                                    </small>
                                    <button type="submit" class="btn btn-secondary add-btn">Add</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <ul class="list-group col-md-4">
                        <div class="margin-20"></div>
                        <li class="list-group-item justify-content-between">
                            <h5>Team members</h5>
                            <span class="badge badge-default badge-pill">{{ user_count }}</span>
                        </li>
                        {% for resp in responsibility_list %}
                            <li class="list-group-item justify-content-between">
                                <a class="link" href="{% url 'profile' resp.user.id %}">
                                    {{ resp.user.first_name }} {{ resp.user.last_name }}
                                </a>
                                <form method="post" action="{% url "team_member_delete" resp.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="close">×</button>
                                </form>
                            </li>
                        {% endfor %}
                        {% if edit_permission %}
                            <div onclick="showForm()" class="col-md-6 offset-md-3">
                                <button class="btn btn-secondary add-btn">
                                    Add student
                                </button>
                            </div>
                        {% endif %}
                    </ul>

                </div>
            </div>

        </div>
    </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 50px;
        }

        .add-btn {
            margin-top: 20px;
        }

        .margin-20 {
            margin: 24px;
        }

        .link {
            text-decoration: none !important;
            color: black;
        }

    </style>

    <script>
        function showForm() {
            var form = document.getElementById('student-form');
            if (form.style.display === 'none') {
                form.style.display = 'block';
            }
            else {
                form.style.display = 'none';
            }
        }

        function myFunction() {
            // Declare variables
            var input, filter, items, i;
            input = document.getElementById('search');
            filter = input.value.toUpperCase();
            items = document.getElementsByClassName('dropdown-item');

            // Loop through all list items, and hide those who don't match the search query
            for (i = 0; i < items.length; i++) {
                if (items[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    items[i].style.display = "";
                } else {
                    items[i].style.display = "none";
                }
            }
        }

        function addText(id, name) {
            var inp1 = document.getElementById('search');
            var inp2 = document.getElementById('search-id');
            inp1.value = name;
            inp2.value = id;
        }
    </script>
{% endblock %}